### ISSUE TITLE
Lograr aceptación oficial como evento afiliado a DevOpsDays

### ISSUE THREAD

**Issue by jantoniuk** [devopsdaysmvd/Info#1]
En https://github.com/devopsdaysmvd/docs/wiki/core-team-email hay un draft de e-mail para ser enviado al global core team.

**Comment by andresantoniuk** [comment]
se envió e-mail a info@devopsdays.org

**Comment by andresantoniuk** [comment]
listo, ya estámos listados en https://www.devopsdays.org/events/2019-montevideo
