### ISSUE TITLE
Genera el primer pull request para la webpage

### ISSUE THREAD

**Issue by xavierverdino** [devopsdaysmvd/Info#3]
Genera el primer pull request para la webpage

COmo un nuevo branch bajo https://github.com/devopsdaysmvd/devopsdays-web

Guiarse por https://github.com/devopsdaysmvd/devopsdays-web/tree/master/utilities/docs/workflow

**Comment by andresantoniuk** [comment]
se hizo el primer PR con únicamente un placeholder para el evento (https://github.com/devopsdays/devopsdays-web/pull/6254) y fue aceptado.

Ahora es necesario seguir trabajando en el contenido. Sugiero fuertemente considerar el [workflow](https://github.com/devopsdaysmvd/devopsdays-web/tree/master/utilities/docs/workflow) de forma que cada organizador local pueda aportar contenido directamente en un branch separado y luego un PR a `master` de https://github.com/devopsdaysmvd/devopsdays-web

Luego de que todos los colaboradores estemos de acuerdo, se realiza el PR hacia el sitio oficial.

Generé entorno en Netify de forma que podemos tener preview del sitio https://devopsdaysmvd.netlify.com y de cada PR que hagamos (ejemplo: https://deploy-preview-1--devopsdaysmvd.netlify.com/events/2019-montevideo)
